server:
  port: 8080

spring:
  application:
    name: homework

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/order
    username: sa
    password:
  sql:
    init:
      encoding: utf-8 # 한글 깨짐 방지(문자 인코딩 설정)
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  use-fqn: true
